# Generated by Django 3.2.5 on 2021-08-13 19:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, validators=[core.validators.length_validator]),
        ),
    ]
