# Generated by Django 3.2.5 on 2021-08-12 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_shop_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderer_first_name', models.CharField(max_length=20)),
                ('orderer_last_name', models.CharField(max_length=20)),
                ('address_street', models.CharField(max_length=20)),
                ('address_city', models.CharField(max_length=20)),
                ('address_country', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_shop_product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
