# Generated by Django 3.2.5 on 2021-08-07 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fashion', 'Fashion'), ('computer', 'Computer'), ('phone', 'Phone'), ('car', 'Car'), ('accommodation', 'Accommodation'), ('accessory', 'Accessory')], max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('state', models.CharField(choices=[('used', 'Used'), ('brand new', 'Brand new')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('image', models.FileField(upload_to='products')),
                ('description', models.TextField(max_length=250)),
                ('location', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
