# Generated by Django 3.2.5 on 2021-08-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
