# Generated by Django 3.2.5 on 2021-08-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop_product', '0003_rename_item_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('Used', 'Used'), ('Brand new', 'Brand new')], max_length=10),
        ),
    ]
