# Generated by Django 3.2.5 on 2021-08-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop_product', '0004_alter_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Computer', 'Computer'), ('Phone', 'Phone'), ('Car', 'Car'), ('Accommodation', 'Accommodation'), ('Accessory', 'Accessory')], max_length=15),
        ),
    ]
